Repository NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-Server, pull requests merged in 2024-05, with the labels that each got.

#2 [FEAT] Project Setting
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/sopt/server/GsHometownServerApplication.java
  src/main/java/org/sopt/server/common/dto/ResponseDto.java
  src/main/java/org/sopt/server/domain/Like.java
  src/main/java/org/sopt/server/domain/Member.java
  src/main/java/org/sopt/server/domain/Product.java
  src/main/java/org/sopt/server/domain/Review.java
  src/main/java/org/sopt/server/exception/CommonException.java
  src/main/java/org/sopt/server/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/server/exception/dto/ErrorCode.java
  src/main/java/org/sopt/server/exception/dto/ExceptionDto.java
  src/test/java/org/sopt/server/GsHometownServerApplicationTests.java
Labels: ⚙️Setting, 🔥Pull Request, 🍀나연

#6 [FEAT] 홈 조회 API 구현
  src/main/java/org/sopt/server/controller/HomeController.java
  src/main/java/org/sopt/server/domain/Banner.java
  src/main/java/org/sopt/server/dto/response/HomeResponseDto.java
  src/main/java/org/sopt/server/dto/response/MonthlyEventsResponseDto.java
  src/main/java/org/sopt/server/repository/BannerRepository.java
  src/main/java/org/sopt/server/service/HomeService.java
Labels: 📬API, ✨ Feature, 🔥Pull Request, 🍀예진

#9 [FEAT] 편의점 category 상품 사전예약 화면 조회 API
  src/main/java/org/sopt/server/controller/ProductController.java
  src/main/java/org/sopt/server/domain/Product.java
  src/main/java/org/sopt/server/dto/response/CategoryProductsDto.java
  src/main/java/org/sopt/server/dto/response/ProductDetailDto.java
  src/main/java/org/sopt/server/dto/response/ProductDto.java
  src/main/java/org/sopt/server/repository/ProductDetailRepository.java
  src/main/java/org/sopt/server/repository/ProductRepository.java
  src/main/java/org/sopt/server/service/ProductService.java
Labels: 📬API, ✨ Feature, 🔥Pull Request, 🍀나연

#12 [FEAT] 편의점 기본 product 사전 예약 화면 조회 API 구현
  src/main/java/org/sopt/server/controller/ProductController.java
  src/main/java/org/sopt/server/domain/Banner.java
  src/main/java/org/sopt/server/domain/type/Category.java
  src/main/java/org/sopt/server/dto/response/AdvanceReservationScreenDto.java
  src/main/java/org/sopt/server/repository/BannerRepository.java
  src/main/java/org/sopt/server/service/HomeService.java
  src/main/java/org/sopt/server/service/ProductService.java
Labels: 📬API, ✨ Feature, 🔥Pull Request, 🍀예진

#11 [FEAT] 좋아요 추가 API
  src/main/java/org/sopt/server/controller/LikeController.java
  src/main/java/org/sopt/server/domain/Like.java
  src/main/java/org/sopt/server/dto/request/LikeAddDto.java
  src/main/java/org/sopt/server/dto/response/LikeDto.java
  src/main/java/org/sopt/server/exception/dto/ErrorCode.java
  src/main/java/org/sopt/server/repository/MemberRepository.java
  src/main/java/org/sopt/server/service/LikeService.java
Labels: 📬API, ✨ Feature, 🔥Pull Request, 🍀나연

#14 [FEAT] 편의점 이벤트 product 사전 예약 화면 조회 API 구현
  src/main/java/org/sopt/server/controller/ProductController.java
  src/main/java/org/sopt/server/dto/request/LikeAddDto.java
  src/main/java/org/sopt/server/dto/response/EventProductsResponseDto.java
  src/main/java/org/sopt/server/service/ProductService.java
Labels: 📬API, ✨ Feature, 🔥Pull Request, 🍀예진

#18 [FIX] 디자인 수정 사항 반영
  src/main/java/org/sopt/server/controller/ProductController.java
  src/main/java/org/sopt/server/domain/type/Category.java
  src/main/java/org/sopt/server/dto/response/AdvanceReservationScreenDto.java
  src/main/java/org/sopt/server/service/ProductService.java
Labels: 🐞Fix, 🔥Pull Request, 🍀예진
